name: Document
on:
  push:
    branches:
      - gh-pages
  pull_request:
  schedule:
    - cron: 0 0 * * *
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: groonga/groonga
          path: groonga
          submodules: recursive
      - name: Prepare ccache
        run: |
          echo "CCACHE_DIR=${PWD}/ccache" >> ${GITHUB_ENV}
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ccache
          key: document-linux-ccache-${{ hashFiles('lib/**', 'src/**', 'plugins/**', 'include/**') }}
          restore-keys: document-linux-ccache-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Install dependencies
        run: |
          groonga/setup.sh
          pip install -r groonga/doc/requirements.txt
          (cd groonga/doc && bundle install)
      - name: Build document
        run: |
          ccache --show-stats --verbose --version || :
          cmake -S groonga -B /tmp/groonga.build --preset=doc
          rm -rf dev/docs dev/ja/docs
          mkdir -p dev/ja
          rake -C groonga release:document:update BUILD_DIR=/tmp/groonga.build GROONGA_ORG_DIR=../dev
          ccache --show-stats --verbose --version || :
          git add -N dev
          if ! git diff --exit-code dev; then
            echo "GIT_DIFF=yes" >> ${GITHUB_ENV}
          fi
      - name: Git push
        if: env.GIT_DIFF == 'yes' && github.event_name == 'schedule'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dev/docs dev/ja/docs
          git commit -m "Update the document"
          git push origin HEAD:gh-pages
