name: Release

on:
  push:
    tags:
      - '*'
jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Wait for upload of `groonga/groonga` asset
        run: |
          run_id=$(gh run list \
                     --repo groonga/groonga \
                     --workflow document.yml \
                     --limit 1 \
                     --branch "v${GITHUB_REF_NAME}" \
                     --status success \
                     --json databaseId \
                     --jq ".[].databaseId")
          gh run watch "${run_id}" --repo groonga/groonga --exit-status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update docs
        run: |
          set -x
          tag_name="${GITHUB_REF_NAME}"
          archive_name="document-${tag_name}"
          wget --quiet "https://github.com/groonga/groonga/releases/download/v${tag_name}/${archive_name}.tar.gz"
          rm -rf docs ja/docs
          tar -xzf "${archive_name}.tar.gz" --strip-components 1
          git add ja docs
          git commit -m "${GITHUB_REF_NAME} has been released!!!"
          git push origin HEAD:gh-pages
      - name: Update blog
        run: |
          set -x
          tag_name="${GITHUB_REF_NAME}"
          rake release:blog:generate
          git add "*/_posts/*-groonga-${tag_name}.md"
          git commit -m "blog: add an article about Groonga ${tag_name}"
          git push origin HEAD:gh-pages
