name: Release

on:
  push:
    tags:
    - '*'
jobs:
  documents:
    name: Documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # todo: Wait for the archive file to be uploaded to Groonga's release page.
      - name: Fetch and extract the archive file
        run: |
          tag_name="${GITHUB_REF_NAME}"
          archive_name="document-${tag_name}"
          wget --quiet "https://github.com/groonga/groonga/releases/download/v${tag_name}/${archive_name}.tar.gz"
          rm -rf docs ja/docs
          tar -xzf "${archive_name}.tar.gz" --strip-components 1
      - name: Update docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ja docs
          git commit -m "${GITHUB_REF_NAME} has been released!!!"
          git push
  blog:
    name: Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Update blog
        run: |
          tag_name="${GITHUB_REF_NAME}"
          rake release:blog:generate
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "*/_posts/*-groonga-${tag_name}.md"
          git commit -m "blog: add an article about Groonga ${tag_name}"
          git push
